signup+footerの作成　＃３
Riku-Obata/frontend-basic-site pull request #5
Opened 2023-08-20 07:24 UTC by Riku-Obata

2023-08-23 12:53 UTC, shimamaru commented on style.css
> +}
不要なセレクタは消した方が良いと思います！

2023-08-23 14:35 UTC, higashiji2000 requested changes

2023-08-23 14:35 UTC, higashiji2000 commented on style.css
> +}
![スクリーンショット 2023-08-23 23 14 20](https://github.com/Riku-Obata/frontend-basic-site/assets/83479175/2f3f3d3b-c7fa-46fa-941c-7c083db6f683)

ブラウザによってbuttonタグに付与されるデフォルトのスタイルによって、枠線がついてしまっています。

また、こんな感じのボタンは別の箇所でもすでに実装した記憶があると思います。 `height` や `padding` といったスタイルは共通しているので、別クラスに切り出して上げると共通化が可能になります。
参考：[DRY原則](https://xn--97-273ae6a4irb6e2hsoiozc2g4b8082p.com/%E3%82%A8%E3%83%83%E3%82%BB%E3%82%A4/DRY%E5%8E%9F%E5%89%87/)

2023-08-23 14:35 UTC, higashiji2000 commented on style.css
> +  line-height: 48.17px;
```suggestion
  line-height: 1.5;
```
line-heightは可能であれば単位なしの値で設定することが望ましいです。
Figma上だと小数点以下の値まで表示されますが、そこまで厳密に実装する必要があるケースは少ないです。
また、小数点以下のpxの扱いはブラウザによって異なるという話もあるため注意が必要です。

参考：
- https://developer.mozilla.org/ja/docs/Web/CSS/line-height
- https://unformedbuilding.com/articles/after-the-decimal-point-in-css/ （10年前の記事なので現在どうなのかは不明）

2023-08-23 14:35 UTC, higashiji2000 commented on style.css
> +  height: 336px;
```suggestion
```

![image](https://github.com/Riku-Obata/frontend-basic-site/assets/83479175/0a7d5887-3441-4999-acad-bac3216e9ca6)
heightを固定してしまうと、textareaをリサイズしたときに突き抜けてしまうのであまり良くありません。
リサイズを不可能にするか、height を設定せず contents に応じて可変にしましょう。

（heightを固定にすると他の要素の高さを変更したときにそれに合わせて調整する必要があるため、後者がおすすめです）

2023-08-23 14:35 UTC, higashiji2000 commented on style.css
> +  background-color: rgba(240, 67, 165, 1);
CSS変数を使ってください！

2023-08-23 14:35 UTC, higashiji2000 commented on style.css
> +  color: rgba(255, 254, 252, 1);
こちらもCSS変数で

2023-08-23 14:35 UTC, higashiji2000 commented on style.css
> +  font-weight: 400;
```suggestion
```

これはなくてもよさそう

2023-08-23 14:35 UTC, Higashiji commented on index.html
> +          />今すぐレッスンを初めて、”Grand”なプレイヤーを目指しましょう!
```suggestion
　　今すぐレッスンを初めて、”Grand”なプレイヤーを目指しましょう!
```
こちらfigma側のミスなのでなくても大丈夫です 🙇 

クラス名に関しては、ケバブケースで `pc-br` とするのが適切かと
もしくは、 `only-pc` みたいな汎用的なクラス名としてしまうのもありですね

2023-08-23 14:35 UTC, higashiji2000 commented on style.css
> +  padding: 60px 40px;
```suggestion
  padding: 60px 40px;
```

ここ以外にも共通しますが、 `height` は可能な限り固定値を持たないようにしましょう。

今回は `padding` と中身のテキストの高さによって内在的に高さが決まるため、わざわざ `height` を設定する必要は無いでしょう。

`height` を設定していると困るケース：
仮に、今後Figmaが修正され、 `@2023 GrandPlayers` という文字の大きさが2倍にする必要が生じたとします。
`height` を設定していた場合は文字の大きさと `.footer` の `height` 2箇所を変更する必要がありますが、`height` を設定せず `padding` と内容によって高さが決定されていた場合、文字の大きさのみ修正すれば `.footer` 全体の高さもいい感じになります。

2023-08-24 05:39 UTC, Riku-Obata commented
修正しました！

2023-08-25 15:36 UTC, higashiji2000 approved these changes
LGTM！

コメントを元に既存実装にも手を入れているのがすごくいい感じです！

あとコミットを細かく分けているのもレビュアーとして助かります✨

2023-08-25 15:36 UTC, higashiji2000 commented on style.css
> +  resize: vertical;
👍

2023-08-25 15:36 UTC, higashiji2000 commented on style.css
> +  line-height: 21.79px;
修正漏れがあるとレビューの往復が一回多くなってしまいます。
サイト制作課題は小規模個人開発であり、厳密さはそこまで求めないのでマージしてOKですが、
案件では気をつけるようにしましょう！

2023-08-25 16:44 UTC, merged